### ISSUE TITLE
Using with Mibew 3.x

### ISSUE THREAD

**Issue by Bert-de-Jong** [AARInnovations/mibew-sound-notification-plugin#3]
I'm trying to use this plug-in with Mibew 3.x, but, so far, to no avail.
I need to put this in public_html/mibew/plugins/SoundNotification/, correct?
But then when I go to https://www.website.com/mibew/operator/plugin it doesn't show up.
I've tried editing the "plugins:" section in configs/config.yml, but this doesn't fix it.
Any suggestions on how I could move forward? Thanks.

**Comment by AARInnovations** [comment]
It is expected that plugin files to be located at your site directory mibew/plugins/AARInnovations/Mibew/Plugin/SoundNotification. Other details on the plugin configuration please find at https://www.aar-innovations.com/mibew-sound-notification-plugin.

**Comment by Bert-de-Jong** [comment]
Using your instructions, it shows up now and I can indeed enable it.

However, from what I can tell the plug-in doesn't work. At least not with Mibew 3.x.
We've tested it by, after enabling your plug-in, having someone enter the chat.
This gave a single *pling* sound (the default functionality of Mibew itself).
We then waited for more than a minute, but Mibew did not give any additional *pling*s.
Perhaps you could give it a try with Mibew 3.x. to verify it works for you.

**Comment by AARInnovations** [comment]
Plugin is successfully working with Mibew 3.1.2 and Chrome 66.

**Comment by Bert-de-Jong** [comment]
Maybe I know what happens here. We have a separate computer just for Mibew, and it's only used to talk with customers. On that computer, focus is (almost) always on the browser window that contains Mibew. I think perhaps this plug-in does not activate if the browser window already has focus. The assumption is probably that a user is active behind the computer that has Mibew. We'll make sure another window has focus if we're not near the Mibew computer. Closing this issue.
