### ISSUE TITLE
Small Documentation Error

### ISSUE THREAD

**Issue by Bert-de-Jong** [AARInnovations/mibew-sound-notification-plugin#4]
On your website, it says the "loop" option has default ["false"](https://aar-innovations.com/mibew-sound-notification-plugin).
However, in the package and on GitHub, it has default ["true"](https://github.com/AARInnovations/mibew-sound-notification-plugin/blob/master/js/users_plugin.js#L47)
(By the way, loop on true is good. I'd say it's what users use this plug-in for.)

**Comment by AARInnovations** [comment]
Thank you for your comment. We will change the plugin description.
